-- Exploratory Data Analysis

--1. How many records are in the dataset?
SELECT COUNT(*) AS total_records
FROM fact_retail_inventory;
-- 73100 records are  in datset


--2. How many stores, products, categories, and regions are there?
SELECT COUNT(DISTINCT store_id) AS total_stores,
COUNT(DISTINCT product_id) AS total_products,
COUNT(DISTINCT category) AS total_categories,
COUNT(DISTINCT region) AS total_regions
FROM fact_retail_inventory;
-- Their are total_stores = 5, products = 20, category = 5, regions = 4

--3.  What is the date range covered by the dataset?
SELECT MIN(date) AS start_date, MAX(date) AS end_date
FROM fact_retail_inventory;
--  data is from date 2022-01-01 TO 2024-01-01

--4.  How are sales distributed across stores?
SELECT store_id, SUM(revenue) AS total_sales
FROM fact_retail_inventory
GROUP BY store_id
ORDER BY total_sales DESC;
-- sales distrubuted as storeId S005 have done highest sales

--5.  How is inventory distributed across stores? inventory = current stock availble 
SELECT store_id, SUM(inventory_level) AS inventory_distrubuted
FROM fact_retail_inventory
GROUP BY store_id
ORDER BY inventory_distrubuted DESC;
--  store id S003 have inventory Level 4047873

--6.  Which product categories have the highest inventory levels?
SELECT category, SUM(inventory_level) AS highest_inventory_level
FROM fact_retail_inventory
GROUP BY category
ORDER BY highest_inventory_level DESC ;
--  Furniture Category have highest inventory level that is 4054223

--7.  Which region generates the highest revenue?

SELECT region, SUM(revenue) AS highest_revenue
FROM fact_retail_inventory
GROUP  BY region
ORDER  BY highest_revenue DESC;
-- Highest Revenue Generated by East region.

--8.  What is the average selling price across product categories?
SELECT category, AVG(price) AS avg_selling_price
FROM fact_retail_inventory
GROUP BY category;
--  Avergae selling price is between 54 to 55


--9. How are records distributed over time (Year/Month)?
SELECT month,year, COUNT(*) AS records_distrubuted
FROM fact_retail_inventory
GROUP BY month,year
ORDER BY records_distrubuted DESC;
-- December 2024 has hoghest records


--10.  Which season records the highest sales?
SELECT seasonality, SUM(revenue) AS highest_sales
FROM  fact_retail_inventory
GROUP BY seasonality
ORDER BY highest_sales DESC;
-- Winter makes a highest sales and Summer amkes lowest sales